#!/usr/bin/env python3
"""
Memory store  (AutoCorp CLI - memory)
=====================================

A small SQLite knowledge base so the assistant gets better over time WITHOUT any
fine-tuning. It records:

  * builds  - every project it has planned/built and how it turned out
  * lessons - reusable knowledge: successful approaches, mistakes, and fixes

Before planning a new request, the orchestrator calls `recall_lessons(request)`
to pull relevant past knowledge into the prompt. After a build, it records the
outcome and any fixes, so future runs benefit.

Recall is a simple keyword match (LIKE over the text columns) - fully local, no
embeddings, no extra dependencies. Good enough to surface "you solved something
like this before", and easy to upgrade later.
"""

import datetime
import json
import os
import re
import sqlite3

from config import DB_PATH, DATA_DIR

# Words too common to be useful as recall keywords.
_STOP = {
    "the", "a", "an", "and", "or", "to", "of", "in", "on", "for", "with", "that",
    "this", "it", "is", "be", "build", "make", "create", "write", "add", "using",
    "use", "app", "code", "please", "can", "you", "me", "my", "i",
}


def _connect() -> sqlite3.Connection:
    os.makedirs(DATA_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=5)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """Create tables if needed. Safe to call repeatedly."""
    try:
        with _connect() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS builds (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts           TEXT NOT NULL,
                    request      TEXT,
                    project_name TEXT,
                    workspace    TEXT,
                    plan_json    TEXT,
                    status       TEXT,
                    summary      TEXT
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS lessons (
                    id        INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts        TEXT NOT NULL,
                    kind      TEXT,          -- success | mistake | fix
                    title     TEXT,
                    problem   TEXT,
                    solution  TEXT,
                    tags      TEXT
                )
                """
            )
            # Planner v2: structured plans, stored and loadable independently of
            # builds (a plan may be generated by `plan` without ever being built).
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS plans (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts           TEXT NOT NULL,
                    request      TEXT,
                    project_name TEXT,
                    project_type TEXT,
                    plan_json    TEXT
                )
                """
            )
    except sqlite3.Error:
        pass


# --------------------------------------------------------------------------- #
# Writing
# --------------------------------------------------------------------------- #
def record_build(request: str, project_name: str, workspace: str,
                 plan: dict, status: str, summary: str = "") -> int:
    try:
        with _connect() as conn:
            cur = conn.execute(
                "INSERT INTO builds (ts, request, project_name, workspace, "
                "plan_json, status, summary) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (datetime.datetime.now().isoformat(), request, project_name,
                 workspace, json.dumps(plan), status, summary),
            )
            return cur.lastrowid
    except (sqlite3.Error, TypeError, ValueError):
        return -1


def record_lesson(kind: str, title: str, problem: str = "", solution: str = "",
                  tags: str = "") -> int:
    try:
        with _connect() as conn:
            cur = conn.execute(
                "INSERT INTO lessons (ts, kind, title, problem, solution, tags) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (datetime.datetime.now().isoformat(), kind, title, problem,
                 solution, tags),
            )
            return cur.lastrowid
    except sqlite3.Error:
        return -1


# --------------------------------------------------------------------------- #
# Plans (Planner v2)
# --------------------------------------------------------------------------- #
def save_plan(plan: dict, request: str = "") -> int:
    """Persist a structured plan. Returns the new plan id, or -1 on failure.
    Never raises."""
    if not isinstance(plan, dict):
        return -1
    init_db()  # make sure the plans table exists even if called standalone
    try:
        with _connect() as conn:
            cur = conn.execute(
                "INSERT INTO plans (ts, request, project_name, project_type, plan_json) "
                "VALUES (?, ?, ?, ?, ?)",
                (datetime.datetime.now().isoformat(), request,
                 plan.get("project_name", ""), plan.get("project_type", ""),
                 json.dumps(plan)),
            )
            return cur.lastrowid
    except (sqlite3.Error, TypeError, ValueError):
        return -1


def load_plan(plan_id: int) -> dict:
    """Load a stored plan by id (returns the plan dict), or None."""
    try:
        with _connect() as conn:
            row = conn.execute(
                "SELECT plan_json FROM plans WHERE id = ?", (plan_id,)
            ).fetchone()
    except sqlite3.Error:
        return None
    if not row:
        return None
    try:
        return json.loads(row["plan_json"])
    except (TypeError, ValueError):
        return None


def latest_plan(project_name: str = None) -> dict:
    """Load the most recent stored plan (optionally for a given project_name)."""
    try:
        with _connect() as conn:
            if project_name:
                row = conn.execute(
                    "SELECT plan_json FROM plans WHERE project_name = ? "
                    "ORDER BY ts DESC, id DESC LIMIT 1", (project_name,)
                ).fetchone()
            else:
                row = conn.execute(
                    "SELECT plan_json FROM plans ORDER BY ts DESC, id DESC LIMIT 1"
                ).fetchone()
    except sqlite3.Error:
        return None
    if not row:
        return None
    try:
        return json.loads(row["plan_json"])
    except (TypeError, ValueError):
        return None


def recent_plans(limit: int = 10) -> list:
    """Recent plan rows (metadata, not the full json), newest first."""
    try:
        with _connect() as conn:
            rows = conn.execute(
                "SELECT id, ts, request, project_name, project_type "
                "FROM plans ORDER BY ts DESC, id DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    except sqlite3.Error:
        return []


# --------------------------------------------------------------------------- #
# Reading / recall
# --------------------------------------------------------------------------- #
def _keywords(text: str) -> list:
    words = re.findall(r"[a-zA-Z][a-zA-Z0-9_+.-]{2,}", (text or "").lower())
    seen, out = set(), []
    for w in words:
        if w in _STOP or w in seen:
            continue
        seen.add(w)
        out.append(w)
    return out


def recall_lessons(request: str, limit: int = 5) -> list:
    """Return lessons whose text overlaps the request keywords, best matches first."""
    keywords = _keywords(request)
    if not keywords:
        return []
    clause = " OR ".join(
        ["(title LIKE ? OR problem LIKE ? OR solution LIKE ? OR tags LIKE ?)"] * len(keywords)
    )
    params = []
    for kw in keywords:
        params.extend([f"%{kw}%"] * 4)
    try:
        with _connect() as conn:
            rows = conn.execute(
                f"SELECT * FROM lessons WHERE {clause} ORDER BY ts DESC LIMIT ?",
                (*params, limit * 3),
            ).fetchall()
    except sqlite3.Error:
        return []

    # Rank by how many distinct keywords each lesson matches.
    scored = []
    for r in rows:
        blob = " ".join(str(r[c] or "") for c in ("title", "problem", "solution", "tags")).lower()
        score = sum(1 for kw in keywords if kw in blob)
        scored.append((score, dict(r)))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [d for _, d in scored[:limit]]


def recent_builds(limit: int = 10) -> list:
    try:
        with _connect() as conn:
            rows = conn.execute(
                "SELECT id, ts, request, project_name, status, summary "
                "FROM builds ORDER BY ts DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    except sqlite3.Error:
        return []


def recent_lessons(limit: int = 20) -> list:
    try:
        with _connect() as conn:
            rows = conn.execute(
                "SELECT id, ts, kind, title, problem, solution, tags "
                "FROM lessons ORDER BY ts DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    except sqlite3.Error:
        return []


def stats() -> dict:
    out = {"builds": 0, "lessons": 0, "successes": 0, "fixes": 0, "plans": 0}
    try:
        with _connect() as conn:
            out["builds"] = conn.execute("SELECT COUNT(*) FROM builds").fetchone()[0]
            out["lessons"] = conn.execute("SELECT COUNT(*) FROM lessons").fetchone()[0]
            out["successes"] = conn.execute(
                "SELECT COUNT(*) FROM lessons WHERE kind='success'").fetchone()[0]
            out["fixes"] = conn.execute(
                "SELECT COUNT(*) FROM lessons WHERE kind='fix'").fetchone()[0]
            try:
                out["plans"] = conn.execute("SELECT COUNT(*) FROM plans").fetchone()[0]
            except sqlite3.Error:
                out["plans"] = 0
    except sqlite3.Error:
        pass
    return out


def format_lessons_for_prompt(lessons: list) -> str:
    """Compact text block of recalled lessons to inject into a model prompt."""
    if not lessons:
        return ""
    lines = ["Relevant lessons from past builds (reuse what applies):"]
    for ls in lessons:
        kind = ls.get("kind", "lesson")
        title = ls.get("title", "")
        sol = ls.get("solution", "")
        lines.append(f"- [{kind}] {title}" + (f" → {sol}" if sol else ""))
    return "\n".join(lines)


if __name__ == "__main__":
    init_db()
    print("memory stats:", stats())
