#!/usr/bin/env python3
"""
Tester Brain engine routing  (AutoCorp CLI - Phase DS5 RED)
===========================================================

Drives the design of DS5: routing TesterBrain's fix generation through the
BaseEngine seam (LocalEngine / ClaudeEngine / DeepSeekEngine) instead of the
hard-wired `llm.generate_json()` call. The build path already routes through
engines; this brings the Tester (the real fix generator behind self-healing) onto
the same abstraction so a repair can be generated by DeepSeek/Claude, not just
local Ollama.

    TesterBrain(executor, engine=<BaseEngine>)
        suggest_fix(...)  -> engine.generate(prompt, system=FIX_SYSTEM_PROMPT)
                          -> parse JSON -> {explanation, filename, new_content}

Pinned design (RED until GREEN implements it; ADDITIVE):
  * TesterBrain.__init__ gains an OPTIONAL `engine=None`. Existing
    `TesterBrain(executor)` / `TesterBrain(executor, model=...)` construction is
    unchanged; with no engine, `suggest_fix` keeps using `llm.generate_json`
    (today's behavior, BACKWARD COMPATIBLE).
  * When an engine IS supplied, `suggest_fix` builds the same prompt and calls
    `engine.generate(prompt, system=FIX_SYSTEM_PROMPT)`, then parses the engine's
    text into the SAME dict contract ({explanation, filename, new_content}); the
    direct `llm.generate_json` path is NOT used.
  * Failure contract preserved: an EngineError from `engine.generate` yields {}
    (mirroring the existing `OllamaError/ValueError -> {}` behavior), so the fix
    loop degrades safely.
  * Engine-agnostic: any BaseEngine (Fake/Local/Claude/DeepSeek) plugs in.

RED: the engine tests fail for MISSING IMPLEMENTATION ONLY - TesterBrain's
constructor does not yet accept `engine`, so each engine-bearing construction
raises
    TypeError: TesterBrain.__init__() got an unexpected keyword argument 'engine'
and `TesterBrain(executor).engine` is an AttributeError. Each failure is reached
inside its own test, so they fail individually. The no-engine backward-compat
guards already pass and must STAY green. `TesterBrain`, `FIX_SYSTEM_PROMPT`,
`Executor`, the gates, `EngineError`, and the concrete engines all already exist
and are imported normally. No production code is added or modified in this phase.

Fully offline: a FakeEngine (and monkeypatched real-engine instances) stand in for
generation - NO model, NO network, NO API key, NO subprocess. The real
`generate()` of Local/Claude/DeepSeek engines is never invoked.
"""

import json

import pytest

from core import llm
from brains.tester import TesterBrain, FIX_SYSTEM_PROMPT
from brains.base_engine import EngineError
from brains.local_engine import LocalEngine
from brains.claude_engine import ClaudeEngine
from brains.deepseek_engine import DeepSeekEngine
from safety.executor import Executor
from safety.gate import AllowAllGate


NEW_CONTENT = "import os\n\n\ndef main():\n    print('ok')\n"
FIX_JSON = json.dumps({
    "explanation": "removed the undefined name",
    "filename": "main.py",
    "new_content": NEW_CONTENT,
})
ERROR = "Traceback (most recent call last):\nNameError: name 'boom' is not defined"
PLAN = {"files": [{"path": "main.py"}]}


class FakeEngine:
    """Offline BaseEngine-shaped stand-in: records calls, returns scripted text
    (or raises). NO model, NO network, NO subprocess."""

    name = "fake"

    def __init__(self, output=FIX_JSON, exc=None):
        self.output = output
        self.exc = exc
        self.calls = []

    def generate(self, prompt, system=""):
        self.calls.append({"prompt": prompt, "system": system})
        if self.exc is not None:
            raise self.exc
        return self.output

    def available(self):
        return True


def _executor():
    return Executor(AllowAllGate())


def _seed(tmp_path, name="main.py", content="boom\n"):
    (tmp_path / name).write_text(content)
    return str(tmp_path)


# =========================================================================== #
# A. Engine injection
# =========================================================================== #
def test_accepts_optional_engine():
    engine = FakeEngine()
    tester = TesterBrain(_executor(), engine=engine)
    assert tester.engine is engine


def test_engine_defaults_to_none():
    # Additive default: no engine supplied -> engine attribute is None.
    tester = TesterBrain(_executor())
    assert tester.engine is None


# =========================================================================== #
# B. Engine delegation
# =========================================================================== #
def test_suggest_fix_uses_injected_engine(tmp_path):
    engine = FakeEngine()
    ws = _seed(tmp_path)
    TesterBrain(_executor(), engine=engine).suggest_fix(ws, "main.py", ERROR, PLAN)
    assert len(engine.calls) == 1                      # generation went through the engine


def test_engine_receives_prompt_payload(tmp_path):
    engine = FakeEngine()
    ws = _seed(tmp_path)
    TesterBrain(_executor(), engine=engine).suggest_fix(ws, "main.py", ERROR, PLAN)
    call = engine.calls[0]
    assert "main.py" in call["prompt"]                 # the failing file
    assert "NameError" in call["prompt"]               # the error output
    assert call["system"] == FIX_SYSTEM_PROMPT         # same system prompt


def test_engine_output_returned_through_contract(tmp_path):
    engine = FakeEngine()
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=engine).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT
    assert result["filename"] == "main.py"


def test_engine_path_bypasses_generate_json(tmp_path, monkeypatch):
    # With an engine, the direct llm.generate_json path must NOT be used.
    def _boom(*a, **k):
        raise AssertionError("llm.generate_json must not be called on the engine path")
    monkeypatch.setattr(llm, "generate_json", _boom)
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=FakeEngine()).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT


# =========================================================================== #
# D. Error handling (engine failure follows existing -> {} behavior)
# =========================================================================== #
def test_engine_exception_returns_empty_dict(tmp_path):
    ws = _seed(tmp_path)
    tester = TesterBrain(_executor(), engine=FakeEngine(exc=EngineError("boom")))
    assert tester.suggest_fix(ws, "main.py", ERROR, PLAN) == {}


# =========================================================================== #
# E. Engine-agnostic design (Fake / DeepSeek / Claude / Local)
# =========================================================================== #
def test_fake_engine_injectable(tmp_path):
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=FakeEngine()).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT


def test_deepseek_engine_compatible(tmp_path, monkeypatch):
    engine = DeepSeekEngine()
    monkeypatch.setattr(engine, "generate", lambda prompt, system="": FIX_JSON)
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=engine).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT


def test_claude_engine_compatible(tmp_path, monkeypatch):
    engine = ClaudeEngine()
    monkeypatch.setattr(engine, "generate", lambda prompt, system="": FIX_JSON)
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=engine).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT


def test_local_engine_compatible(tmp_path, monkeypatch):
    engine = LocalEngine()
    monkeypatch.setattr(engine, "generate", lambda prompt, system="": FIX_JSON)
    ws = _seed(tmp_path)
    result = TesterBrain(_executor(), engine=engine).suggest_fix(
        ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == NEW_CONTENT


# =========================================================================== #
# C. Backward compatibility (no engine) - GUARDS, must STAY green
# =========================================================================== #
def test_llm_path_still_functional_without_engine(tmp_path, monkeypatch):
    ws = _seed(tmp_path)
    monkeypatch.setattr(
        llm, "generate_json",
        lambda prompt, system="", model=None: {
            "explanation": "e", "filename": "main.py", "new_content": "x = 1\n"})
    result = TesterBrain(_executor()).suggest_fix(ws, "main.py", ERROR, PLAN)
    assert result["new_content"] == "x = 1\n"          # legacy llm path unchanged


def test_no_breaking_constructor():
    assert TesterBrain(_executor()) is not None        # legacy 1-arg construction
    assert TesterBrain(_executor(), model="custom-model").model == "custom-model"
