#!/usr/bin/env python3
"""
SQLite Desktop template  (AutoCorp CLI - brains.templates)  [SQLite Gen Phase 4]
===============================================================================

Recognises SQLite-backed desktop app requests ("a customer CRM desktop app with
SQLite", "a GUI inventory manager with a database", ...) and produces a
deterministic plan for a PySide6 desktop app with a SQLite persistence layer:

    project/
    |-- main.py              QApplication entry point (self-terminating headless)
    |-- database.py          connection + init_db() + CREATE TABLE(s)   (deterministic)
    |-- crud.py              CRUD + search + FK queries + counts          (deterministic)
    |-- export.py            CSV export helpers over crud                 (deterministic)
    |-- requirements.txt     PySide6   (sqlite3/csv are in the standard library)
    +-- ui/
        |-- __init__.py      package marker
        +-- main_window.py   QMainWindow: master-detail UI + Export CSV, wired to crud/export

Phase 4 adds CSV export: a deterministic export.py module (export_<table>_csv and
export_<primary>_with_counts_csv), plus an 'Export CSV' button in the UI. database.py,
crud.py, export.py, main.py, requirements.txt and ui/__init__.py are emitted as exact
`content` (written verbatim by the Builder); only ui/main_window.py is generated by
the engine, from a purpose that names the exact crud/export functions to call.

Routing: registered before `pyside6_desktop`; matches only when the request carries
BOTH a data signal (sqlite/database/crud/crm/...) AND a GUI signal
(desktop/gui/window/...), so plain desktop apps still go to `pyside6_desktop`.

Validation gate: execute the entry point headless and require exit 0:
    QT_QPA_PLATFORM=offscreen python main.py
"""

from brains.project_plan import sanitize_name
from brains.templates import sqlite_support

NAME = "sqlite_desktop"

# A request must contain at least one of each group to select this template.
DATA_KEYWORDS = ("sqlite", "database", "crud", "crm", "persistence", "sql")
GUI_KEYWORDS = ("desktop", "gui", "window", "qt", "pyside", "pyside6", "app")

# Trigger / filler words stripped when deriving a project name from the request.
_STOP = {
    "build", "a", "an", "the", "me", "please", "create", "make", "app",
    "application", "desktop", "gui", "window", "pyside6", "pyside", "qt", "with",
    "sqlite", "database", "db", "backed", "using", "and",
}

# The single acceptance command: execute the real entry point, headless.
TEST_COMMAND = "QT_QPA_PLATFORM=offscreen python main.py"

# The exact entry point (same self-terminating pattern as pyside6_desktop: runs
# normally on a desktop; under the offscreen platform it starts the event loop
# then quits immediately so headless tests exit 0). Written verbatim.
MAIN_PY_REFERENCE = '''\
import sys
import os
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QTimer
from ui.main_window import MainWindow


def main():
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    # Headless/CI run (offscreen): start the event loop, then quit immediately so
    # the process exits 0 without a user closing the window. Real desktop runs
    # (no offscreen platform) skip this branch and run interactively.
    if os.environ.get("QT_QPA_PLATFORM") == "offscreen":
        QTimer.singleShot(0, app.quit)
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
'''


def matches(request: str) -> bool:
    text = (request or "").lower()
    has_data = any(k in text for k in DATA_KEYWORDS)
    has_gui = any(k in text for k in GUI_KEYWORDS)
    return has_data and has_gui


def _project_name(request: str) -> str:
    words = [w for w in (request or "").lower().split() if w.isalnum() and w not in _STOP]
    name = "_".join(words[:4]) if words else "sqlite_app"
    name = sanitize_name(name)
    if "app" not in name and "desktop" not in name:
        name = f"{name}_app"
    return name or "sqlite_app"


def _child_section(schema, primary, one):
    """Describe the detail pane for every child table that references the primary."""
    sing = sqlite_support._singular
    lines = []
    for table in schema:
        fk = next((c for c, ref in table.foreign_keys if ref == primary), None)
        if not fk:
            continue
        child_one = sing(table.name)
        child_fields = [c for c, _ in table.columns if c != fk]
        field_params = ", ".join(child_fields)
        lines.append(
            f"  Detail - {table.name}: a QListWidget stored as self.{table.name}_list "
            f"showing crud.get_{table.name}_for_{one}(self.selected_id) when a "
            f"{one} is selected; one QLineEdit per field ({field_params}) stored on "
            f"self; an 'Add {child_one.capitalize()}' QPushButton -> "
            f"crud.add_{child_one}(self.selected_id, {field_params}) then refresh "
            f"this list; and a 'Delete {child_one.capitalize()}' QPushButton -> "
            f"crud.delete_{child_one}(selected_row_id) then refresh."
        )
    return "\n".join(lines)


def _main_window_purpose(schema, app_desc):
    """The Phase 3/4 master-detail UI purpose, derived from the schema: a master
    table (with child counts), a detail pane per child table, and an Export CSV
    button."""
    primary = schema[0]
    table = primary.name
    one = sqlite_support._singular(table)
    fields = [name for name, _ in primary.columns]
    params = ", ".join(fields)
    headers = ", ".join(["Id"] + [f.capitalize() for f in fields])
    first = fields[0] if fields else "value"
    children = sqlite_support._children_of(schema, table)
    count_cols = ", ".join(f"{child}_count" for child, _ in children)

    detail = _child_section(schema, table, one) if children else ""
    master_source = (
        f"crud.get_{table}_with_counts()" if children else f"crud.get_{table}()"
    )
    export_fn = (
        f"export_{table}_with_counts_csv" if children else f"export_{table}_csv"
    )

    purpose = (
        "Define a class named MainWindow that inherits QMainWindow (from "
        "PySide6.QtWidgets). Import the persistence and export layers with exactly: "
        "`import crud` and `import export`. In __init__: call super().__init__(); "
        "set the window title with setWindowTitle(); set the size with "
        "resize(1000, 650); create a central QWidget and pass it to "
        "self.setCentralWidget(central); create a QVBoxLayout and apply it to that "
        "central widget; initialise self.selected_id = None; and call "
        "crud.init_db() FIRST so the database and all tables exist before any "
        "query.\n"
        f"Build a MASTER-DETAIL UI for {table}:\n"
        f"  Master - a QTableWidget stored as self.table listing every {table} via "
        f"{master_source}"
        + (f", with columns ({headers}, {count_cols})" if children
           else f", with columns ({headers})")
        + ". When a row is selected, store its id as self.selected_id, fill the "
        f"{one} input fields from that row, and refresh the detail pane.\n"
        f"  Master controls - one QLineEdit per field ({params}) stored on self "
        f"(e.g. self.{first}_input); an 'Add' QPushButton -> "
        f"crud.add_{one}({params}) then refresh; an 'Edit' QPushButton -> "
        f"crud.update_{one}(self.selected_id, {params}) then refresh; a 'Delete' "
        f"QPushButton -> crud.delete_{one}(self.selected_id) then refresh; a search "
        f"QLineEdit self.search_input + 'Search' QPushButton -> "
        f"crud.search_{table}(self.search_input.text()); a 'Refresh' QPushButton -> "
        f"crud.get_{table}() / {master_source}; and an 'Export CSV' QPushButton -> "
        f"export.{export_fn}('{table}.csv').\n"
        + (detail + "\n" if detail else "")
        + "Use ONLY crud/export functions that exist (the exact names above). Store "
        "every widget a method refers to as an attribute on self so there are NO "
        "undefined attributes, and guard handlers so they do nothing when "
        "self.selected_id is None. Construction must NOT raise: MainWindow() must "
        "build with no arguments and __init__ must run to completion without error "
        "(call crud.init_db() before any query). Do NOT create a QApplication and "
        "do NOT call app.exec() here. This application is: "
        f"{app_desc}."
    )
    return purpose


def build_plan(request: str) -> dict:
    """Return a ProjectPlan-shaped dict for a SQLite-backed PySide6 desktop app."""
    app_desc = (request or "a SQLite desktop application").strip()

    schema = sqlite_support.detect_schema(request)
    primary = schema[0]
    table = primary.name
    one = sqlite_support._singular(table)
    field_names = [name for name, _ in primary.columns]
    table_names = [t.name for t in schema]

    database_code = sqlite_support.schema_database_py(schema)
    crud_code = sqlite_support.schema_crud_py(schema)
    export_code = sqlite_support.export_py(schema)
    main_window_purpose = _main_window_purpose(schema, app_desc)

    files = [
        {
            "path": "requirements.txt",
            "purpose": "Python dependencies (PySide6; sqlite3 and csv are stdlib).",
            "content": "PySide6\n",
        },
        {
            "path": "database.py",
            "purpose": (
                f"Persistence layer: get_connection() (foreign keys enforced), "
                f"init_db(), and CREATE TABLE for {', '.join(table_names)}. "
                "Generated deterministically."
            ),
            "content": database_code,
        },
        {
            "path": "crud.py",
            "purpose": (
                f"CRUD + search + counts helpers for {', '.join(table_names)} using "
                "parameterised SQL. Generated deterministically."
            ),
            "content": crud_code,
        },
        {
            "path": "export.py",
            "purpose": (
                "CSV export helpers (export_<table>_csv + master-view export) over "
                "the crud functions. Generated deterministically."
            ),
            "content": export_code,
        },
        {
            "path": "ui/__init__.py",
            "purpose": "Package marker so `ui` is an importable package.",
            "content": "# ui package\n",
        },
        {"path": "ui/main_window.py", "purpose": main_window_purpose},
        {
            "path": "main.py",
            "purpose": (
                "Application entry point; starts QApplication, shows MainWindow, "
                "and self-quits under QT_QPA_PLATFORM=offscreen so headless runs "
                "exit 0. Generated deterministically."
            ),
            "content": MAIN_PY_REFERENCE,
        },
    ]

    return {
        "project_name": _project_name(request),
        "project_type": "desktop",
        "language": "python",
        "summary": (
            f"A SQLite-backed PySide6 desktop application ({', '.join(table_names)}): "
            f"{app_desc}"
        ),
        "files": files,
        # Dependency-safe: database.py before crud.py (imports it); crud.py before
        # export.py (imports it); the ui package + main_window (imports crud/export)
        # before main.py (imports the window).
        "build_order": [
            "requirements.txt",
            "database.py",
            "crud.py",
            "export.py",
            "ui/__init__.py",
            "ui/main_window.py",
            "main.py",
        ],
        "test_command": TEST_COMMAND,
        "success_criteria": [
            "main.py, database.py, crud.py, export.py, ui/main_window.py and "
            "requirements.txt all exist",
            "requirements.txt contains PySide6",
            f"database.py creates the {', '.join(table_names)} table(s) with "
            "foreign keys enforced and exposes init_db()",
            f"crud.py provides add_{one}, get_{table}, get_{one}, update_{one}, "
            f"delete_{one}, search_{table}, the child CRUD, and "
            f"get_{table}_with_counts using parameterised SQL",
            f"export.py provides CSV export (export_{table}_csv and the master-view "
            "export) over the crud helpers",
            "MainWindow inherits QMainWindow, calls crud.init_db(), and shows a "
            "master table with a detail pane supporting add / edit / delete / "
            "search / refresh / export CSV",
            "`QT_QPA_PLATFORM=offscreen python main.py` starts QApplication, "
            "constructs and shows MainWindow, runs the event loop, and exits 0",
        ],
    }
