#!/usr/bin/env python3
"""
SQLite Desktop template  (AutoCorp CLI - brains.templates)  [SQLite Gen Phase 1]
===============================================================================

Recognises SQLite-backed desktop app requests ("a customer CRM desktop app with
SQLite", "a GUI inventory manager with a database", ...) and produces a
deterministic plan for a PySide6 desktop app with a SQLite persistence layer:

    project/
    |-- main.py              QApplication entry point (self-terminating headless)
    |-- database.py          connection + init_db() + CREATE TABLE   (deterministic)
    |-- crud.py              add / get / update / delete helpers      (deterministic)
    |-- requirements.txt     PySide6   (sqlite3 is in the standard library)
    +-- ui/
        |-- __init__.py      package marker
        +-- main_window.py   QMainWindow wired to crud.*

Determinism: database.py, crud.py, main.py, requirements.txt and ui/__init__.py
are emitted with exact `content`, so the Builder writes them VERBATIM (no model
involvement) - the persistence layer is always correct. Only ui/main_window.py is
generated by the Builder/engine, from a purpose that names the exact crud
functions to call.

Routing: this template MUST be registered before `pyside6_desktop` (which also
matches "desktop"/"app"). It only matches when the request carries BOTH a data
signal (sqlite/database/crud/crm/...) AND a GUI signal (desktop/gui/window/...),
so plain desktop apps still go to `pyside6_desktop`.

Validation: identical acceptance gate to pyside6_desktop - execute the entry
point headless and require exit 0:

    QT_QPA_PLATFORM=offscreen python main.py
"""

from brains.project_plan import sanitize_name
from brains.templates import sqlite_support

NAME = "sqlite_desktop"

# A request must contain at least one of each group to select this template.
DATA_KEYWORDS = ("sqlite", "database", "crud", "crm", "persistence", "sql")
GUI_KEYWORDS = ("desktop", "gui", "window", "qt", "pyside", "pyside6", "app")

# Trigger / filler words stripped when deriving a project name from the request.
_STOP = {
    "build", "a", "an", "the", "me", "please", "create", "make", "app",
    "application", "desktop", "gui", "window", "pyside6", "pyside", "qt", "with",
    "sqlite", "database", "db", "backed", "using", "and",
}

# The single acceptance command: execute the real entry point, headless.
TEST_COMMAND = "QT_QPA_PLATFORM=offscreen python main.py"

# The exact entry point (same self-terminating pattern as pyside6_desktop: runs
# normally on a desktop; under the offscreen platform it starts the event loop
# then quits immediately so headless tests exit 0). Written verbatim.
MAIN_PY_REFERENCE = '''\
import sys
import os
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QTimer
from ui.main_window import MainWindow


def main():
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    # Headless/CI run (offscreen): start the event loop, then quit immediately so
    # the process exits 0 without a user closing the window. Real desktop runs
    # (no offscreen platform) skip this branch and run interactively.
    if os.environ.get("QT_QPA_PLATFORM") == "offscreen":
        QTimer.singleShot(0, app.quit)
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
'''


def matches(request: str) -> bool:
    text = (request or "").lower()
    has_data = any(k in text for k in DATA_KEYWORDS)
    has_gui = any(k in text for k in GUI_KEYWORDS)
    return has_data and has_gui


def _project_name(request: str) -> str:
    words = [w for w in (request or "").lower().split() if w.isalnum() and w not in _STOP]
    name = "_".join(words[:4]) if words else "sqlite_app"
    name = sanitize_name(name)
    if "app" not in name and "desktop" not in name:
        name = f"{name}_app"
    return name or "sqlite_app"


def build_plan(request: str) -> dict:
    """Return a ProjectPlan-shaped dict for a SQLite-backed PySide6 desktop app."""
    app_desc = (request or "a SQLite desktop application").strip()

    table = sqlite_support.detect_entity(request)
    columns = sqlite_support.columns_for(table)
    one = table[:-1] if table.endswith("s") and len(table) > 1 else table
    field_names = [name for name, _ in columns]
    params = ", ".join(field_names)

    database_code = sqlite_support.database_py(table, columns)
    crud_code = sqlite_support.crud_py(table, columns)

    main_window_purpose = (
        "Define a class named MainWindow that inherits QMainWindow (from "
        "PySide6.QtWidgets). Import the persistence layer with exactly: "
        "`import crud`. In __init__: call super().__init__(); set the window "
        "title with setWindowTitle(); set the size with resize(); create a "
        "central QWidget and pass it to self.setCentralWidget(central); create a "
        "QVBoxLayout and apply it to that central widget; and call crud.init_db() "
        "once so the database/table exist. "
        f"Build a simple UI for managing {table}: one QLineEdit per field "
        f"({', '.join(field_names)}), each stored as an attribute on self; an "
        f"'Add' QPushButton whose handler reads those inputs and calls "
        f"crud.add_{one}({params}), then refreshes the list; and a QListWidget "
        "stored as self.list_widget that displays every row returned by "
        f"crud.get_{table}() (one line per row). Use ONLY these crud functions, "
        f"by these exact names: crud.add_{one}({params}); crud.get_{table}(); "
        f"crud.update_{one}(record_id, {params}); crud.delete_{one}(record_id). "
        "Store every widget a method refers to as an attribute on self so there "
        "are NO undefined attributes. Construction must NOT raise: MainWindow() "
        "must build with no arguments and __init__ must run to completion without "
        "error. Do NOT create a QApplication and do NOT call app.exec() here. "
        f"This application is: {app_desc}."
    )

    files = [
        {
            "path": "requirements.txt",
            "purpose": "Python dependencies (PySide6; sqlite3 is stdlib).",
            "content": "PySide6\n",
        },
        {
            "path": "database.py",
            "purpose": (
                f"Persistence layer: get_connection(), init_db(), and the CREATE "
                f"TABLE for the '{table}' table. Generated deterministically."
            ),
            "content": database_code,
        },
        {
            "path": "crud.py",
            "purpose": (
                f"CRUD helpers for {table} (add_{one}/get_{table}/update_{one}/"
                f"delete_{one}) using parameterised SQL. Generated deterministically."
            ),
            "content": crud_code,
        },
        {
            "path": "ui/__init__.py",
            "purpose": "Package marker so `ui` is an importable package.",
            "content": "# ui package\n",
        },
        {"path": "ui/main_window.py", "purpose": main_window_purpose},
        {
            "path": "main.py",
            "purpose": (
                "Application entry point; starts QApplication, shows MainWindow, "
                "and self-quits under QT_QPA_PLATFORM=offscreen so headless runs "
                "exit 0. Generated deterministically."
            ),
            "content": MAIN_PY_REFERENCE,
        },
    ]

    return {
        "project_name": _project_name(request),
        "project_type": "desktop",
        "language": "python",
        "summary": f"A SQLite-backed PySide6 desktop application: {app_desc}",
        "files": files,
        # Dependency-safe: database.py before crud.py (which imports it); the ui
        # package + main_window (imports crud) before main.py (imports the window).
        "build_order": [
            "requirements.txt",
            "database.py",
            "crud.py",
            "ui/__init__.py",
            "ui/main_window.py",
            "main.py",
        ],
        "test_command": TEST_COMMAND,
        "success_criteria": [
            "main.py, database.py, crud.py, ui/main_window.py and "
            "requirements.txt all exist",
            "requirements.txt contains PySide6",
            f"database.py creates the {table} table and exposes init_db()",
            f"crud.py provides add_{one}, get_{table}, update_{one}, "
            f"delete_{one} using parameterised SQL",
            "MainWindow inherits QMainWindow, calls crud.init_db(), and "
            "constructs with no arguments",
            "`QT_QPA_PLATFORM=offscreen python main.py` starts QApplication, "
            "constructs and shows MainWindow, runs the event loop, and exits 0",
        ],
    }
